import type { Metadata } from 'next';
import { PROJECT, V2_CHANGES } from '@/content/project';

export const metadata: Metadata = {
  title: 'The tracker',
  description:
    'RotaGuide is a local-first progressive web app for tracking insulin injection-site rotation. Works offline; data stays on your device.',
};

const APP_URL = 'https://app-rotaguide.vercel.app';

const FEATURES = [
  {
    title: 'One tap to log',
    body: 'Pick the body region, tap the zone matching the port you used. Median logging time in testing was 11.4 seconds against a 15-second target.',
  },
  {
    title: 'A suggestion that understands the plate',
    body: 'The highlighted zone is the one furthest from where you have injected recently, weighted so a site used yesterday counts for more than one used last month.',
  },
  {
    title: 'Repeat warnings with three states',
    body: 'No risk, caution, and warning are visually distinct. A single repeat does not interrupt you the same way a pattern does — otherwise you learn to dismiss the dialog without reading it.',
  },
  {
    title: 'Rotation measured in millimetres',
    body: 'Adherence is the share of consecutive injections at least 20 mm apart, computed in the plate geometry, not a count of how often the zone number changed.',
  },
  {
    title: 'Works with no connection',
    body: 'Installable to a home screen and fully functional offline. The offline bundle is 58 KB gzipped and contains no third-party requests.',
  },
  {
    title: 'Your data stays on your device',
    body: 'History lives in IndexedDB and is never transmitted. Cloud backup exists, is off by default, and states exactly which fields it would send before you enable it.',
  },
] as const;

/**
 * Generated by `pnpm --filter @rotaguide/app screens` from the real
 * build — see apps/app/scripts/capture-screens.ts.
 */
const SCREENS = [
  {
    file: '01-log-light.png',
    caption: 'Log — pick a region, tap the zone you used.',
    alt: 'The Log tab: six body-region buttons, a suggestion banner reading “Suggested next”, and a twelve-segment colour-coded dial with usage counts.',
  },
  {
    file: '02-history-light.png',
    caption: 'History — totals, streak, and rotation score.',
    alt: 'The History tab: three statistics showing total injections, day streak and rotation percentage, above a list of recent injections.',
  },
  {
    file: '03-insights-dark.png',
    caption: 'Insights — zone heatmap and adherence, in dark mode.',
    alt: 'The Insights tab in dark mode: a four-by-three heatmap of zone usage counts with a caption explaining that darker means used more often.',
  },
  {
    file: '04-settings-dark.png',
    caption: 'Settings — guide size, export, and the privacy statement.',
    alt: 'The Settings tab in dark mode, showing guide configuration and data controls.',
  },
] as const;

export default function AppPage() {
  return (
    <>
      <section className="hero">
        <div className="shell narrow">
          <p className="notice">
            <span className="notice__dot" aria-hidden="true" />
            Academic prototype — not a medical device
          </p>
          <h1>The RotaGuide tracker.</h1>
          <p className="lede">
            A local-first progressive web app that mirrors the physical guide&apos;s zones — so the
            number on the plate and the number on the screen mean the same place on your body.
          </p>
          <div className="cta-row">
            <a className="button button--primary" href={APP_URL} rel="noreferrer noopener">
              Open the app
            </a>
            <a
              className="button"
              href={`${PROJECT.repo}/tree/main/apps/app`}
              rel="noreferrer noopener"
            >
              Browse the source
            </a>
          </div>
        </div>
      </section>

      <section>
        <div className="shell">
          <p className="eyebrow">What it does</p>
          <h2 className="section-title">Six things, done carefully.</h2>

          <div className="features">
            {FEATURES.map((feature, i) => (
              <article key={feature.title} className="feature">
                <span className="feature__num">{String(i + 1).padStart(2, '0')}</span>
                <h3>{feature.title}</h3>
                <p>{feature.body}</p>
              </article>
            ))}
          </div>
        </div>
      </section>

      <section>
        <div className="shell">
          <p className="eyebrow">The screens</p>
          <h2 className="section-title">Four tabs.</h2>
          <p className="lede">
            Captured from the real build by a script that seeds the same demo history every time, so
            these can never drift from what the app actually looks like.
          </p>

          <div className="shots">
            {SCREENS.map((screen) => (
              <figure key={screen.file} className="shot">
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={`/screens/${screen.file}`}
                  alt={screen.alt}
                  width={390}
                  height={844}
                  loading="lazy"
                />
                <figcaption>{screen.caption}</figcaption>
              </figure>
            ))}
          </div>
        </div>
      </section>

      <section>
        <div className="shell">
          <p className="eyebrow">Under the hood</p>
          <h2 className="section-title">A tested core with a UI on top.</h2>
          <p className="lede">
            The rotation logic is a pure TypeScript module — no React, no DOM, no clock reads.
            ESLint fails the build if anything in it imports a framework or touches a browser
            global. It sits at 100% statement, branch, function and line coverage across 98 tests,
            including property-based tests asserting invariants that must hold for any possible
            history.
          </p>

          <div className="code">
            <pre>{`// Invariants, checked against thousands of generated histories
adherence  ∈ [0, 1]                       for any log set
recommend  ≠ most recently used zone      whenever history exists
recommend  is deterministic               for a given log set and clock
recommend  is order-independent           however entries are stored`}</pre>
          </div>

          <p
            style={{
              marginTop: 'var(--rg-space-6)',
              fontSize: 'var(--rg-text-sm)',
              color: 'var(--rg-text-muted)',
            }}
          >
            Everything on screen — the suggestion, the adherence score, the risk level — is
            recomputed from your injection history at render time. Nothing derived is stored, so the
            numbers can never drift out of step with the history that produced them.
          </p>
        </div>
      </section>

      <section>
        <div className="shell">
          <p className="eyebrow">v1 → v2</p>
          <h2 className="section-title">What the rewrite actually changed.</h2>
          <p className="lede">
            The original shipped as a single 56 KB HTML file. It worked, and the final report named
            its own limitations. This is what addressing them looked like.
          </p>

          <div className="changes">
            {V2_CHANGES.map((change) => (
              <article key={change.title} className="change">
                <h3>{change.title}</h3>
                <p className="change__before">
                  <span className="change__tag">v1</span>
                  {change.before}
                </p>
                <p className="change__after">
                  <span className="change__tag">v2</span>
                  {change.after}
                </p>
              </article>
            ))}
          </div>

          <div className="callout">
            <p className="callout__label">Judge for yourself</p>
            <p>
              The original app is still deployed, unchanged, at <a href="/v1/index.html">/v1</a>.
              Compare it against{' '}
              <a href={APP_URL} rel="noreferrer noopener">
                the current build
              </a>{' '}
              rather than taking the list above on trust.
            </p>
          </div>
        </div>
      </section>

      <section>
        <div className="shell narrow">
          <p className="eyebrow">Accessibility</p>
          <h2 className="section-title">Built for the people who would actually use it.</h2>
          <p className="lede">
            The intended users include older adults with reduced vision, neuropathy, and arthritis.
            That makes accessibility a functional requirement, not a finishing pass.
          </p>
          <ul className="unverified" style={{ marginTop: 'var(--rg-space-8)' }}>
            <li>Minimum 44 px tap targets throughout, and one-handed reach on a phone.</li>
            <li>
              Complete keyboard operation: arrow keys move between zones and wrap around, dialogs
              trap focus and return it on close.
            </li>
            <li>
              Recently-used zones are marked by hatching as well as opacity, so the state does not
              depend on colour vision.
            </li>
            <li>Status changes are announced through polite live regions.</li>
            <li>
              <code>axe-core</code> runs against every route in both light and dark themes on every
              push.
            </li>
          </ul>
        </div>
      </section>
    </>
  );
}
